# _config.yml - Minimal working version for GitHub Pages

# REMOVE 'theme: none' completely (it's causing the error)
# Instead use:
theme: jekyll-theme-minimal  # This is a valid empty theme

# Disable all plugins to prevent interference
plugins: []

# Force proper Markdown processing
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Explicitly exclude GitHub's default files
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
